# Generated by Django 5.1.1 on 2024-10-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_pic', models.CharField(blank=True, default='https://png.pngtree.com/element_our/20190528/ourmid/pngtree-cartoon-mobile-phone-image_1127554.jpg', max_length=255, null=True)),
                ('back_pic', models.CharField(blank=True, default='https://png.pngtree.com/element_our/20190528/ourmid/pngtree-cartoon-mobile-phone-image_1127554.jpg', max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Google', 'Google'), ('OnePlus', 'OnePlus'), ('Xiaomi', 'Xiaomi'), ('Realme', 'Realme'), ('Oppo', 'Oppo'), ('Vivo', 'Vivo')], default='Apple', max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('display_size', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('memory_internal', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('total_sold', models.IntegerField(default=0)),
                ('available_count', models.IntegerField(default=10)),
                ('is_available', models.BooleanField(default=True)),
                ('discount_available', models.BooleanField(default=False)),
                ('discount_persen', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('brand', 'model'), name='no_duplicate_model')],
            },
        ),
    ]
